kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-egress-operator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*" 
- apiGroups:
  - "networking.k8s.io"
  resources:
  - hostsubnets
  - netnamespaces
  verbs:
  - "*"   
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-egress-operator
rules:
# leader election   
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - "*"
#Metrics  
- apiGroups:
  - ""
  resources:
  - services
  - namespaces
  verbs:
  - "*"
#Metrics  
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs: 
  - "get"
  - "list"
# Metrics  
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
# Metrics  
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - openshift-egress-operator
  verbs:
  - "update"

